import type { Metadata } from "next";
import Vertnavbar from "../../app/Vertnavbar"
import Searchbar from "../../app/Searchbar"

export const metadata: Metadata = {
  title: "Summarist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Searchbar />
        <Vertnavbar />
        {children}
      </body>
    </html>
  );
}